[check]
exclude = [
        '.venv',
        'fruit/fruit.f90',
        'fruit/fruit_mpi.f90',
]
ignore = [
    'C003',    # implicit-external-procedures
    'C061',    # missing-intent
    'C071',    # assumed-size
    'C072',    # assumed-size-character-intent
    'C141',    # missing-exit-or-cycle-label
    'E001',    # syntax-error
]
